// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQsehvVl_BihRqUSOtUXAy_Pc-nARh8s',
    appId: '1:464361943996:web:a89bc29a1f16273bacb1b9',
    messagingSenderId: '464361943996',
    projectId: 'ecommerce-app-b5380',
    authDomain: 'ecommerce-app-b5380.firebaseapp.com',
    storageBucket: 'ecommerce-app-b5380.appspot.com',
    measurementId: 'G-KBL11YLHNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAogsEvNssxQHt6OekNQmaGeoL447rao_A',
    appId: '1:464361943996:android:0b6374d2f82a18c9acb1b9',
    messagingSenderId: '464361943996',
    projectId: 'ecommerce-app-b5380',
    storageBucket: 'ecommerce-app-b5380.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAvO9p7AiI7UaKIDIyuKJJgnznr_H5FP8',
    appId: '1:464361943996:ios:22b89e6662d9b604acb1b9',
    messagingSenderId: '464361943996',
    projectId: 'ecommerce-app-b5380',
    storageBucket: 'ecommerce-app-b5380.appspot.com',
    iosClientId: '464361943996-vkgdo2mpfr1q483lckjnvicagb8eg6cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAvO9p7AiI7UaKIDIyuKJJgnznr_H5FP8',
    appId: '1:464361943996:ios:c23e0b5df83aaec7acb1b9',
    messagingSenderId: '464361943996',
    projectId: 'ecommerce-app-b5380',
    storageBucket: 'ecommerce-app-b5380.appspot.com',
    iosClientId: '464361943996-1bpa7q8jvn54jkt3meui776f3643vbld.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
